// Generated by gencpp from file dlite_simulator/Cell.msg
// DO NOT EDIT!


#ifndef DLITE_SIMULATOR_MESSAGE_CELL_H
#define DLITE_SIMULATOR_MESSAGE_CELL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace dlite_simulator
{
template <class ContainerAllocator>
struct Cell_
{
  typedef Cell_<ContainerAllocator> Type;

  Cell_()
    : x(0)
    , y(0)  {
    }
  Cell_(const ContainerAllocator& _alloc)
    : x(0)
    , y(0)  {
  (void)_alloc;
    }



   typedef int32_t _x_type;
  _x_type x;

   typedef int32_t _y_type;
  _y_type y;





  typedef boost::shared_ptr< ::dlite_simulator::Cell_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::dlite_simulator::Cell_<ContainerAllocator> const> ConstPtr;

}; // struct Cell_

typedef ::dlite_simulator::Cell_<std::allocator<void> > Cell;

typedef boost::shared_ptr< ::dlite_simulator::Cell > CellPtr;
typedef boost::shared_ptr< ::dlite_simulator::Cell const> CellConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::dlite_simulator::Cell_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::dlite_simulator::Cell_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::dlite_simulator::Cell_<ContainerAllocator1> & lhs, const ::dlite_simulator::Cell_<ContainerAllocator2> & rhs)
{
  return lhs.x == rhs.x &&
    lhs.y == rhs.y;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::dlite_simulator::Cell_<ContainerAllocator1> & lhs, const ::dlite_simulator::Cell_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace dlite_simulator

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::dlite_simulator::Cell_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dlite_simulator::Cell_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dlite_simulator::Cell_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dlite_simulator::Cell_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dlite_simulator::Cell_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dlite_simulator::Cell_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::dlite_simulator::Cell_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bd7b43fd41d4c47bf5c703cc7d016709";
  }

  static const char* value(const ::dlite_simulator::Cell_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xbd7b43fd41d4c47bULL;
  static const uint64_t static_value2 = 0xf5c703cc7d016709ULL;
};

template<class ContainerAllocator>
struct DataType< ::dlite_simulator::Cell_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dlite_simulator/Cell";
  }

  static const char* value(const ::dlite_simulator::Cell_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::dlite_simulator::Cell_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 x\n"
"int32 y \n"
;
  }

  static const char* value(const ::dlite_simulator::Cell_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::dlite_simulator::Cell_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Cell_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::dlite_simulator::Cell_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::dlite_simulator::Cell_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<int32_t>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<int32_t>::stream(s, indent + "  ", v.y);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DLITE_SIMULATOR_MESSAGE_CELL_H
