// Generated by gencpp from file dlite_simulator/SensorData.msg
// DO NOT EDIT!


#ifndef DLITE_SIMULATOR_MESSAGE_SENSORDATA_H
#define DLITE_SIMULATOR_MESSAGE_SENSORDATA_H

#include <ros/service_traits.h>


#include <dlite_simulator/SensorDataRequest.h>
#include <dlite_simulator/SensorDataResponse.h>


namespace dlite_simulator
{

struct SensorData
{

typedef SensorDataRequest Request;
typedef SensorDataResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SensorData
} // namespace dlite_simulator


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::dlite_simulator::SensorData > {
  static const char* value()
  {
    return "6d7179c08c0bd6c2f0b77bbe9e2ae2dc";
  }

  static const char* value(const ::dlite_simulator::SensorData&) { return value(); }
};

template<>
struct DataType< ::dlite_simulator::SensorData > {
  static const char* value()
  {
    return "dlite_simulator/SensorData";
  }

  static const char* value(const ::dlite_simulator::SensorData&) { return value(); }
};


// service_traits::MD5Sum< ::dlite_simulator::SensorDataRequest> should match
// service_traits::MD5Sum< ::dlite_simulator::SensorData >
template<>
struct MD5Sum< ::dlite_simulator::SensorDataRequest>
{
  static const char* value()
  {
    return MD5Sum< ::dlite_simulator::SensorData >::value();
  }
  static const char* value(const ::dlite_simulator::SensorDataRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::dlite_simulator::SensorDataRequest> should match
// service_traits::DataType< ::dlite_simulator::SensorData >
template<>
struct DataType< ::dlite_simulator::SensorDataRequest>
{
  static const char* value()
  {
    return DataType< ::dlite_simulator::SensorData >::value();
  }
  static const char* value(const ::dlite_simulator::SensorDataRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::dlite_simulator::SensorDataResponse> should match
// service_traits::MD5Sum< ::dlite_simulator::SensorData >
template<>
struct MD5Sum< ::dlite_simulator::SensorDataResponse>
{
  static const char* value()
  {
    return MD5Sum< ::dlite_simulator::SensorData >::value();
  }
  static const char* value(const ::dlite_simulator::SensorDataResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::dlite_simulator::SensorDataResponse> should match
// service_traits::DataType< ::dlite_simulator::SensorData >
template<>
struct DataType< ::dlite_simulator::SensorDataResponse>
{
  static const char* value()
  {
    return DataType< ::dlite_simulator::SensorData >::value();
  }
  static const char* value(const ::dlite_simulator::SensorDataResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DLITE_SIMULATOR_MESSAGE_SENSORDATA_H
